version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3005:3000"
    volumes:
      - ./frontend/frontend:/movie/frontend
      - project-vol:/movie/

  backend:
      build:
        context: ./backend
      command: >
        sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:4000"
      ports:
        - "3006:4000"
      volumes:
        - ./backend/app:/movie/app
        - dev-static-data:/vol/web
        - project-vol:/movie/
      environment:
        - DB_HOST=db
        - DB_NAME=newdb
        - DB_USER=devuser
        - DB_PASS=changeme2
        - DEBUG=1
      depends_on:
        - db

  db:
    image: postgres:16-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=newdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme2
      - POSTGRES_HOST_AUTH_METHOD=md5
      - PGDATA=/var/lib/postgresql/data/pgdata
volumes:
  dev-db-data:
  dev-static-data:
  project-vol:

